# Generated by Django 6.0.5 on 2026-05-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faculty",
            options={"verbose_name_plural": "Faculties"},
        ),
    ]
